import Foundation

/// Wrapper for the Go download server framework generated by gomobile bind.
class GoDownloaderServer {
  /// Start the server on a background thread. Returns the port number (0 on failure).
  /// dataDir: 数据持久化目录路径，由 Flutter 传入。
  class func startServer(dataDir: String) -> Int {
    let className = "Mobile"
    if let cls = NSClassFromString(className) {
      let sel = NSSelectorFromString("startServer:")
      if cls.responds(to: sel) {
        let port = cls.perform(sel, with: dataDir).takeUnretainedValue() as! Int
        return port
      }
    }
    return 0
  }

  class func stopServer() {
    let className = "Mobile"
    if let cls = NSClassFromString(className) {
      let sel = NSSelectorFromString("stopServer")
      if cls.responds(to: sel) {
        cls.perform(sel)
      }
    }
  }
}
